### ISSUE TITLE
Sigils inside strings should not be highlighted

### ISSUE THREAD

**Issue by yyyc514** [elixir-lang/elixir-tmbundle#128]
This is not right, is it?
![screen shot 2017-06-01 at 9 36 55 am](https://cloud.githubusercontent.com/assets/6473/26682276/edc70a40-46ad-11e7-8231-d2fd6a57ac06.png)

**Comment by josevalim** [comment]
Looks wrong, yes. :)

**Comment by yyyc514** [comment]
Nevermind - upgraded the package and seems it's been fixed. :)
