### ISSUE TITLE
TextMate version 2.0-beta.7.1 - installation failed

### ISSUE THREAD

**Issue by Javix** [elixir-lang/elixir-tmbundle#37]
I tried to install the Textmate bundle as suggested and it failed as follows:
```
Bundles  osascript -e 'tell app "TextMate" to reload bundles'
23:37: syntax error: A identifier can’t go after this identifier. (-2740)
```
Anyway, the bundle is in the Textmate bundle list with all its submenus and options. Is it normal ?
Any ideas ? 
OS: OS X 10.10.3 x64

Thank you.

**Comment by rod-eligible** [comment]
I have exactly the same issue with textmate 2.0-beta.7.4
