### ISSUE TITLE
New changes break syntax highlight on Sublime Text 3

### ISSUE THREAD

**Issue by jannekai** [elixir-lang/elixir-tmbundle#50]
Seems like the latest changes break syntax highlighting when using Sublime Text 3 or at least reduce it's functionality. Function parameters are all shown with same color and worse, the module name is not highlighted in statements like below:

use Behaviour
require Logger
Enum.map [1,2,3], fn x -> x + 1 end

Here is a couple of screenshots showing what it looks like for me:

The last working one was commit 56efe6116ff92a6979ba94ff2722486e3f440583 
![working-56efe6116ff92a6979ba94ff2722486e3f440583](https://cloud.githubusercontent.com/assets/320559/9797378/7869e172-5803-11e5-9cc4-212f49a9ed03.png)

The next commit seems to break function parameters:
![breaking-1334da9633fec669e80487f448e1b001b2767a6c](https://cloud.githubusercontent.com/assets/320559/9797405/98d042b2-5803-11e5-88bd-34f14adf2b7d.png)

And the current master 1a062c327dcb418462c8d5351990d0cdc13545f3 has breaking Module highlights.
![master-1a062c327dcb418462c8d5351990d0cdc13545f3](https://cloud.githubusercontent.com/assets/320559/9797423/b68574f8-5803-11e5-9cfd-4141cba9a8b8.png)

I do like the fact of trying to highlight functions, but I think the module highlighting is more important for readability, at least in my codebase. Not sure if this issue is related to Sublime Text 3 or does it happen with other editors supporting textmate syntax format.

**Comment by endersstocker** [comment]
@jannekai What scope selector are you using for module names (e.g. MyStruct, Enum)? What happens if you use `support.module`?
