### ISSUE TITLE
What is the "~/.config/sublime-text-2/Packages" path for windows?

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [elixir-lang/elixir-tmbundle#71]
cd ~/.config/sublime-text-2/Packages # If you are on Linux
cd ~/Library/Application\ Support/Sublime\ Text\ 2/Packages # If you are on Mac
cd xxx # if you are on Windows

**On my machine:**
C:\Users\Charles\AppData\Roaming\Sublime Text 3\Packages

Please confirm if this is the correct equivalent for windows, and kindly update the read-me to reflect this.

**some errors:**

C:\>cd tools

C:\Tools>git clone git://github.com/elixir-lang/elixir-tmbundle Elixir
Cloning into 'Elixir'...
remote: Counting objects: 572, done.
Receiving objects:  73% (418/572), 36.00 KiB | 50.00 KiB/s    572
Receiving objects: 100% (572/572), 108.85 KiB | 50.00 KiB/s, done.
Resolving deltas: 100% (271/271), done.
Checking connectivity... done.
error: Invalid path 'Preferences/Symbol List: Module.tmPreferences'
error: Invalid path 'Preferences/Symbol List: Private Function.tmPreferences'
error: Invalid path 'Preferences/Symbol List: Public Function.tmPreferences'

C:\Tools>

Thanks!

**Comment by CharlesOkwuagwu** [comment]
Windows file names cannot have **:** in them for hence these 3 are invalid:

'Preferences/Symbol List: Module.tmPreferences'
'Preferences/Symbol List: Private Function.tmPreferences'
'Preferences/Symbol List: Public Function.tmPreferences'

**Comment by endersstocker** [comment]
@CharlesOkwuagwu I don’t have access to Windows at the moment. Can you verify that `cd %HOMEPATH%\AppData\Roaming\Sublime Text 3\Packages` gets you to that directory? What version of Windows are you using?

**Comment by CharlesOkwuagwu** [comment]
windows 10

Yes it does

**Comment by josevalim** [comment]
Thanks for taking of those issues @endersstocker, very appreciated!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
