### ISSUE TITLE
Single line function's `do` being rendered as keyword list

### ISSUE THREAD

**Issue by binaryseed** [elixir-lang/elixir-tmbundle#73]
I updated recently and I've found that in a single-line function, the `do:` and `else:` look like they're being treated as a keyword list instead of the standard operator

```elixir
def start_link(_), do: Supervisor.start_link(_args)
```

<img width="647" alt="screen shot 2015-11-08 at 10 22 11 pm" src="https://cloud.githubusercontent.com/assets/39946/11027138/32d6e3ac-8667-11e5-8a81-0ed362cce90e.png">

Previously, it'd look like this:

<img width="644" alt="screen_shot_2015-11-08_at_10_20_34_pm" src="https://cloud.githubusercontent.com/assets/39946/11027132/18da3e04-8667-11e5-8e13-fcc18ac809e6.png">

cc/ @endersstocker I see you're tagged on a handful of these recent issues, could you help track this one down? I tried fixing it myself, but the `tmLanguage` format isn't exactly straightforward...

**Comment by endersstocker** [comment]
In a single-line function, `do` and `else` _are_ a keyword list.

**Comment by binaryseed** [comment]
Yes, I'm aware of that, but `do` and `else` have special significance. In the 'old' screenshot, you can see that in line 7, there's additional items in the keyword list that are treated as I would expect - the `also:` key is interpreted as a normal key. 

If there isn't interest in changing this in the main repo, could you perhaps help me understand which sections of the `tmLanguage` are responsible for denoting the `do:` here as a keyword list?

Another thing to note is that even in the keyword list interpretation, there is another ` ` space character that is being caught by the match, which is visible since my color scheme colors the background of the keys as well - and it's only happening on the `do: ` key, not any additional keys, and regardless of order...

<img width="380" alt="screen shot 2015-11-09 at 7 50 11 am" src="https://cloud.githubusercontent.com/assets/39946/11038192/93950e54-86b6-11e5-9400-cbf8e259c56f.png">

**Comment by binaryseed** [comment]
Relevant fixes have been merged in https://github.com/elixir-lang/elixir-tmbundle/pull/74
