### ISSUE TITLE
File Icons

### ISSUE THREAD

**Issue by nate** [elixir-lang/elixir-tmbundle#81]
The [elixir file icons](http://monosnap.sutton.me/elixir_icons.png) for the file drawer are looking pretty plain. [Ruby has some sweet ones](http://monosnap.sutton.me/20151208190539-ruby_icons.png) but I can't find anything in the ruby bundle that specifies these icons. Do you happen to know how to change these? I'd be willing to put something together to spiff it up a bit and contribute it back.

Thanks!

**Comment by optikfluffel** [comment]
@nate Any progress on that one?

**Comment by nate** [comment]
Negative, I couldn't find where they were set up and moved on. I'm closing until someone who knows how to do it chimes in.
