### ISSUE TITLE
snippets named with : will not work on windows

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [elixir-lang/elixir-tmbundle#87]
The new snippets:

if:, unless:, if: else:, and unless: else will not work on windows...

Would you name them something different?

**Comment by josevalim** [comment]
Yes, we should. :) /cc @jefffederman

**Comment by jefffederman** [comment]
Done! :-)

https://github.com/elixir-lang/elixir-tmbundle/pull/88

**Comment by CharlesOkwuagwu** [comment]
Actually it was the file names that needs changing... you still have file names containing ":"

the file named Snippets/if:.tmSnippet for example

Windows file names cannot have a ":"

**Comment by jefffederman** [comment]
@CharlesOkwuagwu I'm assuming that mean the snippet name can have a colon in it, then. See the Javascript snippet for 'Object key – key: "value"'.

<img width="717" alt="key_value" src="https://cloud.githubusercontent.com/assets/163454/12044196/95664e42-ae5b-11e5-8ef6-fafcb9227439.png">

**Comment by CharlesOkwuagwu** [comment]
Yeah, it's the snippet "file name" that's the issues. 
Sorry for not making that clear initially.
