### ISSUE TITLE
Add interpolated string Snippet

### ISSUE THREAD

**Issue by dougal** [elixir-lang/elixir-tmbundle#96]
When in a string, typing `$` should expand to `${}` with the cursor between the brackets. Also when text is selected, and `$` is typed, the text should be wrapped in brackets with the `$` preceding them.

This would be identical in behaviour to the `#` snippet in the Ruby package: https://github.com/textmate/ruby.tmbundle/blob/master/Snippets/embed%20string%20variable.plist

I had a go at doing this myself, but my lack of familiarity with the santa descriptors let me down.

**Comment by josevalim** [comment]
Do you mean `#` as well? Elixir uses `#` for interpolation in strings as well.

**Comment by dougal** [comment]
Ah, yes, sorry. I do mean `#`. Too much ES6 yesterday.
